# Generated by Django 4.0.3 on 2022-04-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('artist', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('song_file', models.FileField(blank=True, null=True, upload_to='')),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('beats_per_min', models.CharField(blank=True, max_length=5, null=True)),
                ('energy', models.CharField(blank=True, max_length=5, null=True)),
                ('danceability', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
