# Generated by Django 4.0.3 on 2022-04-04 00:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('bpm', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('energy', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('danceability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('loudness', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0)])),
                ('liveness', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('acousticness', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('speechiness', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='beats_per_min',
        ),
        migrations.RemoveField(
            model_name='song',
            name='danceability',
        ),
        migrations.RemoveField(
            model_name='song',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_file',
        ),
        migrations.AddField(
            model_name='song',
            name='image_link',
            field=models.CharField(default='w', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='song_link',
            field=models.CharField(default='w', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('ATL_HIP_HOP', 'Atlanta hip hop'), ('AUSTRALIAN_POP', 'Australian pop'), ('BIG_ROOM', 'Big room'), ('BOY_BAND', 'Boy band'), ('BROSTEP', 'Brostep'), ('CANADIAN_HIP_HOP', 'Canadian hip hop'), ('CANADIAN_POP', 'Canadian pop'), ('COUNTRY_RAP', 'Country rap'), ('DANCE_POP', 'Dancepop'), ('DFW_RAP', 'DFW rap'), ('EDM', 'EDM'), ('ELECTROPOP', 'Electropop'), ('ESCAPE_ROOM', 'Escape room'), ('LATIN', 'Latin'), ('PANAMANIAN_POP', 'Panamanian pop'), ('POP', 'Pop'), ('POP_HOUSE', 'Pop house'), ('R_AND_B_ES', 'R&B en espanol'), ('REGGAETON', 'Reggaeton'), ('REGGAETON_FLOW', 'Reggaeton flow'), ('TRAP_MUSIC', 'Trap music')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MusicApp.songdetail'),
        ),
    ]
