# Generated by Django 4.0.3 on 2022-04-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignIn',
        ),
    ]
